#!/usr/bin/env python3
from hal import *
import os

os.system("realtime start")

c = component("hello")

port_in = c.newpin("port-in", HAL_PORT, HAL_IN)
port_out = c.newpin("port-out", HAL_PORT, HAL_OUT)

in_s = c.newpin("in-s", HAL_S32, HAL_IN)
out_s = c.newpin("out-s", HAL_S32, HAL_OUT)

in_u = c.newpin("in-u", HAL_U32, HAL_IN)
out_u = c.newpin("out-u", HAL_U32, HAL_OUT)

in_f = c.newpin("in-f", HAL_FLOAT, HAL_IN)
out_f = c.newpin("out-f", HAL_FLOAT, HAL_OUT)


in_io = c.newpin("in-io", HAL_BIT, HAL_IO)
out_io = c.newpin("out-io", HAL_BIT, HAL_IO)


c.ready()





#test signed in/out pins 
sigNew("testSig-S", HAL_S32)
sigLink("hello.in-s", "testSig-S")
sigLink("hello.out-s", "testSig-S")
out_s.value = -100
assert in_s.value == -100, "in_s.value should be -100. got {0}".format(in_s.value)
out_s.value = 34435
assert in_s.value == 34435, "in_s.value should be 34435. got {0}".format(in_s.value)


#test unsigned in/out pins
sigNew("testSig-U", HAL_U32)
sigLink("hello.in-u", "testSig-U")
sigLink("hello.out-u", "testSig-U")
out_u.value = 65535
assert in_u.value == out_u.value, "in_u.value should be {0}. got {0}".format(out_u.value, in_u.value)


#test float pins
sigNew("testSig-F", HAL_FLOAT)
sigLink("hello.in-f", "testSig-F")
os.system("halcmd sets testSig-F -1000.0")

assert in_f.value == -1000.0
sigLink("hello.out-f", "testSig-F")

out_f.value = 333.333
assert in_f.value == 333.333

#test io bool
sigNew("testSig-IO", HAL_BIT)
sigLink("hello.in-io", "testSig-IO")
sigLink("hello.out-io", "testSig-IO")

out_io.value = False
assert in_io.value == False
out_io.value = True
assert in_io.value == True

in_io.value = False
assert out_io.value == False



#now test hal port
sigNew("testSig-PORT", HAL_PORT)
sigLink("hello.port-in", "testSig-PORT")
sigLink("hello.port-out", "testSig-PORT")

assert port_in.size() == 0
assert port_out.size() == 0

#make sure to allocate a port on the signal
os.system('halcmd sets testSig-PORT 9')

assert port_in.size() == 9
assert port_out.size() == 9


assert port_out.writable() == 8
assert port_in.readable() == 0


port_out.waitWritable(8)
assert port_out.write("hello")
assert port_out.writable() == 3

assert port_in.readable() == 5
assert port_in.read(2) == b"he"
assert port_in.peek(10) == b""
assert port_in.peek(3) == b"llo"
assert port_in.readable() == 3
assert port_in.read(3) == b"llo"

assert port_in.readable() == 0
assert port_out.write("hello")
assert port_in.read(5) == b"hello"

assert port_in.readable() == 0
assert port_in.read(5) == b''


assert port_out.writable() == 8

assert port_out.write("12345678")

assert port_in.readable() == 8
assert port_out.writable() == 0

assert port_in.read(8) == b"12345678"

c.exit()
os.system("halrun -U")
exit(0)
